[aws]
aws_access_key_id = "AKIA3M6PACHQYSHRY7OT"
aws_secret_access_key = "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"
aws_region = "us-east-2"
s3_bucket_name = "dgat-streamlit-storage-app-2025"

[gmail]
gmail_user = "carlwanghy@gmail.com"
gmail_app_password = "gkkyqllvamfytmhr"
admin_email = "haw309@pitt.edu"